### ISSUE TITLE
the math operator "/" throws a parse error

### ISSUE THREAD

**Issue by gertheber** [codeschool/sqlite-parser#11]
In a select such as 

`select
  9 / 3 as COL1
from 
  table1`

the parser will throw an error. The same issue can be observed at your demo website. Let me know if you need any more info

![screen shot 2016-02-01 at 5 54 51 pm](https://cloud.githubusercontent.com/assets/16946738/12734185/f5c48328-c90c-11e5-9482-cace870681dc.png)

**Comment by gertheber** [comment]
Thanks Nick

**Comment by nwronski** [comment]
That was a pretty silly oversight on my part. Keep them coming, I really appreciate the bug reports.

**Comment by gertheber** [comment]
Not to worry at all, I have been using the parser for over a month now. And it is impressive. You did a great job.
