### ISSUE TITLE
Select statement fail to parse if more than 2 fields listed in Order By Clause

### ISSUE THREAD

**Issue by gertheber** [codeschool/sqlite-parser#13]
Given statement:

`select 
 fred, 
 barney, 
 wilma,
 betty,
 city
from 
  flintstones_table
where
  city = 'bedrock'
order by
fred,
barney,
wilma`

Will fail parsing. Can be observed on demo site as well.

If wilma is removed from order by, query parses correctly

**Comment by nwronski** [comment]
You are a bug finding machine. Thanks!

**Comment by gertheber** [comment]
Thanks for the fixes Nick! We are using parser in production as of this week, so this helps.
