### ISSUE TITLE
Mathematical operations in where

### ISSUE THREAD

**Issue by anvog** [codeschool/sqlite-parser#20]
`SELECT * FROM temptable where value1 = ((value2 * 5) - value3)`

The statement above will throw the error.

> Syntax error found near Binary Expression

Brackets should be fine. 
Any other way to structure the equations?

**Comment by nwronski** [comment]
It looks like the grammar isn't happy with the parenthesis on the left side (`(value2 * 5)`) of the expression. Your example is definitely valid. While I look into a fix for this issue, the following is currently accepted: `SELECT * FROM temptable where value1 = (value2 * 5 - value3)`

**Comment by nwronski** [comment]
Based on further investigation, the expression parsing works for simple expressions, but is not obeying order of operations or correctly composing complex expressions. For example:

``` sql
-- parsed as -(1 * (2+3)) instead of (-1) * (2 + 3)
SELECT * FROM t where -1 * (2 + 3)

-- parsed as 3 + (4 * (5 > 20)) instead of (3 + (4 * 5)) > 20
SELECT * FROM t where 3 + 4 * 5 > 20
```

I will need to rewrite the expression parsing grammar for the next release to:
- [ ] Obey order of operations: `*` is higher than `+`, etc...
- [ ] Compose in the correct order: unary expressions, then binary expressions, then logical and/or (`AND`, `OR`), etc...
- [ ] Allow for nesting parenthesis on either side of a binary expression

Expect these changes in release `v0.15.0`.

**Comment by nwronski** [comment]
@anvog I just released a beta version of the parser that contains the fix for the issue you were experiencing [0.15.0-beta](https://github.com/codeschool/sqlite-parser/releases/tag/v0.15.0-beta).

You can install it via npm using (for now):

``` 
npm i sqlite-parser@beta
```

Let me know if you encounter any more problems, thanks!

**Comment by nwronski** [comment]
Whoops, didn't mean to close this one just yet. Will close after 0.15.0 is out of beta.

**Comment by nwronski** [comment]
Closing this one, but still need `beta` flag to install at the moment. 

```
npm i sqlite-parser@beta
```
