### ISSUE TITLE
AST to query conversion

### ISSUE THREAD

**Issue by sibijohn72** [codeschool/sqlite-parser#21]
Hi, is there any way to build the query from a generated AST? 
I need to append a few values to insert and update scripts every time a query is submitted and obviously editing the AST is easier so is there any way to do that?

**Comment by nwronski** [comment]
Unfortunately, there is not currently a way to do this as far as I know. We would need something like the [escodegen](https://github.com/estools/escodegen) tool that exists for JavaScript (e.g., esprima) that operates on the AST generated by sqlite-parser.
