### ISSUE TITLE
SyntaxError when using \' in values list

### ISSUE THREAD

**Issue by philippsimon** [codeschool/sqlite-parser#24]
Hi all,
I found today your library and liked it a lot.

Sadly I only found a little bug when I tested it on a bigger database:

When adding `\'` into a string in an insert values list the following error is thrown:
`SyntaxError: Syntax error found near VALUES Clause (SELECT Statement)`

It can be tested with an updated version of the [basic-insert.sql](https://github.com/codeschool/sqlite-parser/blob/master/test/sql/insert/basic-insert.sql) test:
```SQL
INSERT INTO concessions (item, size, id, price)
VALUES ('Lay\'s Nachos', 'Regular', null, null),
       ('Pizza', null, 8, 2.00);
```

I tried to fix it in the grammar.pegjs but I gave up. I hope you can fix it soon.

**Comment by nwronski** [comment]
@philippsimon, according to the SQLite spec, `\'` is not considered valid string escape syntax.

> A string constant is formed by enclosing the string in single quotes ('). A single quote within the string can be encoded by putting two single quotes in a row - as in Pascal. C-style escapes using the backslash character are not supported because they are not standard SQL.
> [reference](http://www.sqlite.org/lang_expr.html)

You can get your query to parse correctly by escaping single quotes as `''` within a string literal:

``` sql
INSERT INTO concessions (item, size, id, price)
VALUES ('Lay''s Nachos', 'Regular', null, null),
       ('Pizza', null, 8, 2.00);
```

**Comment by philippsimon** [comment]
@nwronski thanks! Didn't know that before.
