### ISSUE TITLE
Node Structure Change: Add variant to condition type

### ISSUE THREAD

**Issue by jdrew1303** [codeschool/sqlite-parser#34]
![image](https://cloud.githubusercontent.com/assets/2535432/19790133/8feb721c-9cad-11e6-9b2c-c0c0e9ba6114.png)

Currently this node does not have a `variant` only a `type`. `when` and `else` conditions have a `format` but not a `variant`.  This makes recursing in the AST difficult.

**Comment by nwronski** [comment]
Yes, this group of nodes has a lot of inconsistency: `IF EXISTS` and `IF NOT EXISTS` which I have reworked to be a little more consistent across the different places these can appear:

- Use `expression` node in `condition` for `IF NOT EXISTS`. `NOT EXISTS`, and `EXISTS` modifiers instead of a string value

``` sql
create table if not exists foo(id int)
```

<details>
  <summary>CREATE TABLE Statement AST</summary>
  ``` json
{
  "type": "statement",
  "name": {
    "type": "identifier",
    "variant": "table",
    "name": "foo"
  },
  "variant": "create",
  "format": "table",
  "definition": [
    {
      "type": "definition",
      "variant": "column",
      "name": "id",
      "definition": [],
      "datatype": {
        "type": "datatype",
        "variant": "int",
        "affinity": "integer"
      }
    }
  ],
  "condition": [
    {
      "type": "condition",
      "variant": "if",
      "condition": {
        "type": "expression",
        "variant": "exists",
        "operator": "not exists"
      }
    }
  ]
}
```
</details>

``` sql
drop table if exists foo
```

<details>
  <summary>DROP TABLE Statement AST</summary>
  ``` json
{
  "type": "statement",
  "target": {
    "type": "identifier",
    "variant": "table",
    "name": "foo"
  },
  "variant": "drop",
  "format": "table",
  "condition": [
    {
      "type": "condition",
      "variant": "if",
      "condition": {
        "type": "expression",
        "variant": "exists",
        "operator": "exists"
      }
    }
  ]
}
```
</details>

``` sql
select a
where not exists (select b)
```

<details>
  <summary>NOT EXISTS Expression AST</summary>
  ``` json
{
  "type": "statement",
  "variant": "select",
  "result": [
    {
      "type": "identifier",
      "variant": "column",
      "name": "a"
    }
  ],
  "where": [
    {
      "type": "expression",
      "format": "unary",
      "variant": "exists",
      "expression": {
        "type": "statement",
        "variant": "select",
        "result": [
          {
            "type": "identifier",
            "variant": "column",
            "name": "b"
          }
        ]
      },
      "operator": "not exists"
    }
  ]
}
```
</details>

**Comment by nwronski** [comment]
Included in latest `sqlite-parser@beta` release [v1.0.0-rc2](https://github.com/codeschool/sqlite-parser/releases/tag/v1.0.0-rc2).

**Comment by jdrew1303** [comment]
Sorry about the original issue. It sounded a bit blunt 🤔 I do most of my work on this at night. 😜 

New nodes are working perfect. Almost no work on my part to fit them into the generator. 👍 I haven't hit any issues with them either. So they're good to go. Thanks for the work on this. I appreciate it.

**Comment by nwronski** [comment]
@jdrew1303 Awesome, I think we are getting pretty close now. Have you found any other issues since the last round of changes? This might be last call for changes before I release v1.0.0.
