### ISSUE TITLE
Bug? Brackets are not parsing properly in binary between statements 1.0.0@beta

### ISSUE THREAD

**Issue by jdrew1303** [codeschool/sqlite-parser#35]
So this is a bit of a weird one. If you take the following test: 

```sql
select *
from hats
where
  x || y BETWEEN x * 2 and x * 3
```
and add brackets around the expressions (keeping the operator precidence intact) then it will refuse to parse the right expression of between `((x * 2) and (x * 3))`:

```sql
select *
from hats
where
  ((x || y) BETWEEN ((x * 2) and (x * 3)));
```

The generator adds brackets to all groupings generated (to make it explicit what the order should be). The first expectation in the suite is that it should parse with no errors. Second is comparing output with input sql.

**Comment by nwronski** [comment]
@jdrew1303 Let me say first that I really appreciate you taking the time to find these issues. I may not be able to get to all of them immediately as I only work on the parser when I have free time outside of work, so bear with me.

This one is an interesting one. The grammar for `BETWEEN` according to the [docs](https://www.sqlite.org/syntax/expr.html) does not allow `expr BETWEEN (expr AND expr)`. Trying it out on SQL Fiddle, WebSQL gave the error `could not prepare statement (1 near ")": syntax error)` and SQL.js gave `TypeError: Cannot read property 'substring' of undefined`.

**Comment by jdrew1303** [comment]
@nwronski No problem. This is a side project for me in between freelance jobs so I understand.  :raising_hand: If there are any issues that I can help with just let me know. Im more than happy to help 👍 

I've been playing around with the between syntax also. It's a strange one. The behaviour also varies from one implementation to another. :frowning_man: This seems to be expected behaviour so I guess it's good to go. Ill hit the sqlite docs beforehand if I come across anything else like this.
