### ISSUE TITLE
Issue with Object.assign is not a function

### ISSUE THREAD

**Issue by sekhar0797** [codeschool/sqlite-parser#43]

**Comment by willsoto** [comment]
Depending on your environment, `Object.assign` might not be available. You should polyfill fill it if that is the case.

**Comment by sekhar0797** [comment]
hi , thanks for the info....i have tried itbut i am unable to execute the
same and i am using npm package.json....could you please let me know how to
use polyfill in this case....

**Comment by willsoto** [comment]
[Here is a package](https://www.npmjs.com/package/object-assign) that will polyfill just `Object.assign` for you. Load it before this script. Please let me know if that resolves the issue for you.

**Comment by sekhar0797** [comment]
can we sync in fb...i can send my files and please let me know where to
change files and all

**Comment by willsoto** [comment]
No I am afraid not. It should be as simple as `npm install object-assign` and then just adding that script to your page however you are already doing that. Do you use webpack or browserify?

**Comment by sekhar0797** [comment]
I am not using either webpack or browserify ... am using package.json and gruntfile.js

**Comment by willsoto** [comment]
How do you load scripts?

**Comment by sekhar0797** [comment]
by using grunt uglify and 
<script src="scripts/bower_components/sqlite-parser.js?ver=@statics.version@"></script> in one of the HTML

**Comment by willsoto** [comment]
[Here](https://github.com/ljharb/object.assign) is a bower version you could use

**Comment by nwronski** [comment]
Not sure where all the other replies in this thread went, but, the parser is available as a single JavaScript file for browser environments at [dist/sqlite-parser.js](https://github.com/codeschool/sqlite-parser/blob/master/dist/sqlite-parser.js). No need for an `Object.assign()` polyfill with the browser version in the `dist/` folder, you can just include `dist/sqlite-parser.js` on the page instead of the Node version in `lib/`.

**Comment by sekhar0797** [comment]
i am using the file from dist folder only. still getting the below issue.

Error: Object doesn't support property or method 'assign'

**Comment by sekhar0797** [comment]
it is failing in IE only
