### ISSUE TITLE
Support for Interval

### ISSUE THREAD

**Issue by Tamirklein** [codeschool/sqlite-parser#48]
I'm trying to use the parser with a WHERE condition containing the following:
 WHERE _PARTITIONTIME > timestamp(DATE_SUB(CURRENT_DATE(), INTERVAL 14 DAY))

But it's not working

What will be the best approach to resolve this?

**Comment by nwronski** [comment]
I believe INTERVAL is part of MySQL but not SQLite. [stackoverflow question](https://stackoverflow.com/questions/1101182/what-are-the-sqlite-equivalents-of-mysqls-interval-and-utc-timestamp).

**Comment by avizaviz** [comment]
I see. However I'm trying to use your solution over bigQuery and obviously, this needs some adjustments, as BQ standard Sql doesn't follow sqlLite standard.
Was trying to get the best way to adjust your parser to support this as it can have a significant added value to the offering.

**Comment by Tamirklein** [comment]
I see. However I'm trying to use your solution over bigQuery and obviously, this needs some adjustments, as BQ standard Sql doesn't follow sqlLite standard.
Was trying to get the best way to adjust your parser to support this as it can have a significant added value to the offering.
One of the main issues was with the interval function.
