### ISSUE TITLE
Problem with reserved identifiers

### ISSUE THREAD

**Issue by ghalimi** [codeschool/sqlite-parser#5]
It looks like identifiers like "date", "time", and "timestamp" are reserved.

For example, this will generate an error:

    SELECT * FROM quakes WHERE date > 40998

Is there any way to work around that?

**Comment by nwronski** [comment]
As best as I can tell, this is against the SQLite rules. To use reserved words as column names you can enclose them in single quotes or brackets: `'date'` or `[date]`.
