### ISSUE TITLE
Feature Request: add stringify method

### ISSUE THREAD

**Issue by lifeiscontent** [codeschool/sqlite-parser#50]
from what I can tell, you can build an AST from the parser, but theres no way to go back to a string.

Is this a feature contained in another package somewhere? Or are there plans on adding this?

**Comment by lvivier** [comment]
@lifeiscontent this has been discussed before (#23). @jdrew1303 created two packages that should do what you want:

- https://github.com/jdrew1303/sqlgenerate
- https://github.com/jdrew1303/sqltraverse
