### ISSUE TITLE
Error thrown when using intersect.

### ISSUE THREAD

**Issue by mstStudent** [codeschool/sqlite-parser#6]
I was trying out your demo and tried the following sql query and get '[2, 1] Syntax error found near INTEGER Datatype Name (FROM Clause)' in your demo site, when I tried it a different project it says something like expecting newline, semi-colon , etc, but found I instead.

SELECT a, b FROM table1
INTERSECT
SELECT * FROM (SELECT a, b FROM table2
               EXCEPT
               SELECT a, b FROM table3)

however if I change intersect to union as so, then no errors are thrown

SELECT a, b FROM table1
union
SELECT * FROM (SELECT a, b FROM table2
               EXCEPT
               SELECT a, b FROM table3)

Is this a bug or is intersect something that hasn't been added quite yet?

**Comment by nwronski** [comment]
This is a good catch. It turns out that the parser picks up on `INT` instead of the full keyword `INTERSECT`. `UNION` `UNION ALL` `INTERSECT` and `EXCEPT` are all allowed by the parser but this bug is keeping you from using `INTERSECT`.

**Comment by nwronski** [comment]
This should now be fixed by 5edb732c62b07fc79e22fb4701bf798987f35b29. Let me know if you still experience any issues. Thanks @mstStudent!
