### ISSUE TITLE
Failes to parse this

### ISSUE THREAD

**Issue by jimmywarting** [codeschool/sqlite-parser#7]
CREATE TABLE unique_index_data (
      index_id integer NOT NULL,
      value blob NOT NULL,
      object_store_id integer NOT NULL,
      object_data_key blob NOT NULL,
      FOREIGN KEY (index_id) REFERENCES object_store_index (id),
      FOREIGN KEY (object_store_id, object_data_key) REFERENCES object_data (object_store_id, key),
      PRIMARY KEY(index_id, value)
    ) WITHOUT ROWID

And this:

    CREATE TABLE foo (id unique, text)

**Comment by nwronski** [comment]
It looks like these issues relate to using reserved keywords as column names. As best as I can tell, this is against the SQLite rules. Trying the first one out on SQLFiddle, it looks like it works in WebSQL but not SQL.js so it might be considered a gray area.

To use reserved words as column names you can enclose them in single quotes or brackets: `'key'` or `[key]`.
