### ISSUE TITLE
Column Alias Names Cannot start with IN.

### ISSUE THREAD

**Issue by gertheber** [codeschool/sqlite-parser#9]
If you alias a column in a select statement with a name that starts with IN (ex: INV), the parser interprets the IN as a expression;

Example:
select  INVACT.invact_id INID,
        INVACT.trndte REPORT_DATE
   from invact INVACT

In this example the parser see IN of INID as the IN operator makes result[0] an
<img width="510" alt="screen shot 2016-01-28 at 5 43 48 pm" src="https://cloud.githubusercontent.com/assets/16946738/12661307/d26eb2e6-c5e6-11e5-8523-c214edf13cef.png">
 expression. In this case  
 INVACT.invact_id becomes the left and ID becomes the right.

**Comment by gertheber** [comment]
Thanks Nick
Gerry

**Comment by nwronski** [comment]
I have published [a new version containing this fix](https://github.com/codeschool/sqlite-parser/releases/tag/v0.12.1) that is now also available on npm. Thank you for the bug report!
